---
- hosts: webservers
  tasks:
    - name: Make sure that we can connect to the machine
      ping:

    - name: Stop Tomcat
      shell: /opt/apache-tomcat-8.5.88/bin/shutdown.sh

    - name: Remove Tomcat
      file:
        path: /opt/apache-tomcat-8.5.88
        state: absent

    - name: remove user "tomcat"
      user:
        name: tomcat
        state: absent

    - name: remove group "tomcat"
      group:
        name: tomcat
        state: absent
