---
- hosts: webservers
  vars:
    - http_port: 8080
    - tomcat_version: 8.5.83
    
  tasks:
    - name: JDK Installation
      apt:
        name: default-jdk
        update_cache: yes
    
    - name: add group "tomcat"
      group: name=tomcat

    - name: add user "tomcat"
      user: name=tomcat group=tomcat createhome=yes

    - name: Download Tomcat
      get_url: url=https://archive.apache.org/dist/tomcat/tomcat-8/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz dest=/opt/apache-tomcat-{{ tomcat_version }}.tar.gz

    - name: Create Tomcat Directory
      file: path=/opt/tomcat state=directory 
      
    - name: Extract Tomcat archive
      command: tar zxvf /opt/apache-tomcat-{{ tomcat_version }}.tar.gz -C /opt
      
    - name: Moving Tomcat Content
      command: mv /opt/apache-tomcat-{{ tomcat_version }}/* /opt/tomcat

    - name: Change ownership of Tomcat installation
      file: path=/opt/tomcat owner=tomcat group=tomcat state=directory recurse=yes

    - name: Change the working directory to Tomcat Apache before running Tomcat Apache
      shell: nohup /opt/tomcat/bin/startup.sh


  root@ip-172-31-31-43:/home/ubuntu# vi tomcatinstall.yml 

---
- hosts: webservers
  become: yes
  vars:
    appName: java-sample.war
  tasks:
     - name: Install JDK package
       apt: name=default-jdk update_cache=yes state=latest

     - name: Install Tomcat10 package
       apt: name=tomcat10 update_cache=yes state=latest

     - name: Install Tomcat10-admin package
       apt: name=tomcat10-admin update_cache=yes state=latest

     - name: Restart Service
       service: name=tomcat10 state=restarted

     - name: copy war
       get_url: url=https://tomcat.apache.org/tomcat-7.0-doc/appdev/sample/sample.war dest=/opt/tomcat/webapps/{{ appName }} owner=tomcat group=tomcat mode=0744

     - name: Deploy Java code
       shell: |
         git clone https://github.com/anujdevopslearn/MavenBuild.git
         cd /tmp/code
         mvn clean install
         cp target/*.war /var/lib/tomcat10/webapps/custom-java.war
